[project]
name = "bycycle.webui"
version = "1.0a1.dev0"
description = "byCycle web API"
authors = [{ name = "Wyatt Baldwin", email = "code@wyattbaldwin.com" }]
license = "GPL-3.0-or-later"

requires-python = ">=3.14"

dependencies = [
    "runcommands>=1.0a74.dev0",
]

[tool.uv.sources]
"runcommands" = { path = "../../runcommands", editable = true }

[project.urls]
homepage = "https://bycycle.org/"
repository = "https://github.com/bycycle-org/bycycle.webui"
